models/articles_category.py
from services.article_service import ArticleService

class ArticlesCategoryModel:
  def __init__(self) -> None:
    pass

  def GetArticlesByCategory(self, category: str) -> list:
    article_service = ArticleService()
    return article_service.GetArticlesByCategory(category)

models/create_article.py
from entities.article import Article
from services.article_service import ArticleService

class CreateArticleModel:
  def __init__(self) -> None:
    pass

  def CreateArticle(self, form: dict):
    article = Article(
      category=form['article-category'],
      title=form['article-title'],
      content=form['article-content'])
    
    article_service = ArticleService()
    article_service.CreateArticle(article)
    

models/main_page.py
from entities.article import Article
from services.article_service import ArticleService

class MainPageModel:
  def __init__(self) -> None:
    pass

  def GetMainArticle(self) -> Article:
    article_service = ArticleService()
    return article_service.GetLatestArticle()

  def GetArticlesToDisplay(self) -> list:
    categories = ["1","2","3","4"]
    
    articles_to_display = []
    article_service = ArticleService()

    for category in categories:
      article_to_add = article_service.GetLatestArticleByCategory(category)
      if article_to_add != None:
        articles_to_display.append(article_to_add)

    return articles_to_display

models/single_article.py
from entities.article import Article
from services.article_service import ArticleService

class SingleArticleModel:
  def __init__(self) -> None:
    pass

  def GetArticle(self, id: int) -> Article:
    article_service = ArticleService()
    return article_service.GetArticle(id)

__init__.py
from flask import Flask, render_template
from controllers.articles import articles_bp
from models.main_page import MainPageModel

app = Flask(__name__)
app.register_blueprint(articles_bp)
  
@app.route('/')
def index():
  model = MainPageModel()
  main_article = model.GetMainArticle()
  articles_to_display = model.GetArticlesToDisplay()
  return render_template("index.html", main_article=main_article, articles_to_display=articles_to_display)

if __name__ == "__main__":
  app.run(debug=True)

controllers/articles.py
from flask import render_template, Blueprint, request, redirect, url_for
from models.create_article import CreateArticleModel
from models.articles_category import ArticlesCategoryModel
from models.single_article import SingleArticleModel

articles_bp = Blueprint("articles", __name__, url_prefix="/articles")

@articles_bp.route('/create-article', methods=('GET', 'POST'))
def create_article():
  if request.method == 'POST':
    model = CreateArticleModel()
    model.CreateArticle(request.form)
    return redirect(url_for("index"))

  return render_template("create_article.html")

@articles_bp.route('/categories')
def articles_categories():
  return render_template("categories.html")

@articles_bp.route('/category/<category>')
def articles_category(category):
  model = ArticlesCategoryModel()
  articles = model.GetArticlesByCategory(category)
  return render_template("articles_category.html", articles_to_display=articles)

@articles_bp.route('/article/<int:article_id>')
def article(article_id):
  model = SingleArticleModel()
  article = model.GetArticle(article_id)
  return render_template("view_article.html", article=article)

templates/articles_category.html
{% extends 'shared/_layout.html' %}

{% block main %}

<div class="row mb-2 pt-3">

  {% for article in articles_to_display %}
    <div class="col-md-12">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-5 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-secondary">{{article['DisplayCategory']}}</strong>
          <h3 class="mb-1">{{article['Title']}}</h3>
          <div class="mb-2 text-muted">{{article['DisplayCreated']}}</div>
          <p class="card-text mb-2">{{ article['Content'][0:50]}}...</p>
          <a href="{{url_for('articles.article', article_id=article['Id'])}}" class="stretched-link text-secondary">Continue reading</a>
        </div>
      </div>
    </div>
  {% endfor %}

</div>

{% endblock main %}

templates/categories.html
{% extends 'shared/_layout.html' %}

{% block main %}

<div class="row mb-2 pt-3">

  <div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-5 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <a href="{{ url_for('articles.articles_category', category=1)}}">
          <strong class="d-inline-block mb-2 text-secondary">Tech</strong>
        </a>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-5 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <a href="{{ url_for('articles.articles_category', category=2)}}">
          <strong class="d-inline-block mb-2 text-secondary">Business</strong>
        </a>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-5 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <a href="{{ url_for('articles.articles_category', category=3)}}">
          <strong class="d-inline-block mb-2 text-secondary">World</strong>
        </a>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-5 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <a href="{{ url_for('articles.articles_category', category=4)}}">
          <strong class="d-inline-block mb-2 text-secondary">Lifestyle</strong>
        </a>
      </div>
    </div>
  </div>

</div>

{% endblock main %}

templates/create_article.html
{% extends 'shared/_layout.html' %}

{% block main %}

<form method="post">
  <div class="form-group mb-4">
    <label class="mb-1" for="articleTitle">Title</label>
    <input 
      type="text" class="form-control mb-1" id="articleTitle" name="article-title"
      aria-describedby="articleTitle" value="{{ request.form['title'] }}" placeholder="Enter a Title">
    <small id="articleBoost" class="form-text text-muted">Make It Unique.</small>
  </div>

  <div class="form-group mb-4">
    <label class="mb-1" for="articleCategory">Category</label>
    <select name="article-category" class="form-select" id="articleCategory">
      <option value="1">Tech</option>
      <option value="2">Business</option>
      <option value="3">World</option>
      <option value="4">Lifestyle</option>
    </select>
  </div>

  <label class="mb-1">Content</label>
  <div class="form-floating mb-4">
    <textarea
      name="article-content"
      id="articleContent" 
      class="form-control" 
      placeholder="Leave a comment here"  
      style="height: 200px">{{request.form['content']}}</textarea>
    <label for="articleContent">What's new?</label>
  </div>

  <button type="submit" class="btn btn-outline-dark">Post It!</button>
</form>

{% endblock main %}

templates/index.html
{% extends 'shared/_layout.html' %}

{% block main %}

<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 fst-italic">{{ main_article['Title']}}</h1>
    <p class="lead my-3">{{ main_article['Content'][0:300]}}...</p>
    <p class="lead mb-0">
      <a href="{{url_for('articles.article', article_id=main_article['Id'])}}" 
         class="text-white fw-bold">Continue reading...
      </a>
    </p>
  </div>
</div>

<div class="row mb-2 pt-3">
  <h2 class="mb-4">Latest Articles</h3>

  {% for article in articles_to_display %}
    <div class="col-md-12">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-5 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-secondary">{{article['DisplayCategory']}}</strong>
          <h3 class="mb-1">{{article['Title']}}</h3>
          <div class="mb-2 text-muted">{{article['DisplayCreated']}}</div>
          <p class="card-text mb-2">{{ article['Content'][0:50]}}...</p>
          <a href="{{url_for('articles.article', article_id=article['Id'])}}" class="stretched-link text-secondary">Continue reading</a>
        </div>
      </div>
    </div>
  {% endfor %}

</div>

{% endblock main %}

templates/shared/_footer.html
<div class="container">
  <footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center justify-content-center">
      <small class="mb-3 mb-md-0 text-muted">© 2023 Complex Talk</small>
    </div>
  </footer>
</div>

templates/shared/_layout.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Import bootstrap 5 styling -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
          crossorigin="anonymous">

    <link rel="stylesheet" href="">
  </head>
  <body class="d-flex flex-column h-100">

    {% include 'shared/_navbar.html' %}
    
    <main class="flex-shrink-0">
      <div class="container">
        {% block main %} 
        {% endblock %}
      </div>
    </main>

    {% include 'shared/_footer.html' %}

    <!-- Import bootstrap 5 Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
            crossorigin="anonymous"></script>
  </body>
</html>

templates/shared/_navbar.html
<div class="container">
  <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
        <path 
        d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
      </svg>
    </a>
    
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><a href="{{ url_for('index')}}" class="nav-link px-2 link-dark">Home</a></li>
      <li><a href="{{ url_for('articles.articles_categories')}}" class="nav-link px-2 link-dark">Categories</a></li>
      <li><a href="{{ url_for('articles.create_article')}}" class="nav-link px-2 link-dark">Post</a></li>
    </ul>

    <div class="col-md-3 text-end"></div>
  </header>
</div>

templates/view_article.html
{% extends 'shared/_layout.html' %}

{% block main %}

<div class="row mb-2 pt-3">
  
  <div class="col-md-12">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-5 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <strong class="d-inline-block mb-2 text-secondary">{{article['DisplayCategory']}}</strong>
        <h3 class="mb-1">{{article['Title']}}</h3>
        <div class="mb-2 text-muted">{{article['DisplayCreated']}}</div>
        <p class="card-text mb-2">{{ article['Content']}}</p>
      </div>
    </div>
  </div>

</div>

{% endblock main %}